### ISSUE TITLE
PDM pyproject

### ISSUE THREAD

**Issue by moshfrid** [ninoseki/vscode-mogami#38] opened 2024-05-26 16:42 UTC
Worked as of version 0.0.19, but version 0.0.20 breaks compatibility with pyproject.toml generated/used by PDM

**Comment by ninoseki** [comment] 2024-05-26 16:55
Could you share pyproject.toml, please?

**Comment by ninoseki** [comment] 2024-05-26 17:14
It's my first time to use PDM. So I may miss something but it works in my env.
<img width="430" alt="Screenshot 2024-05-27 at 2 10 57" src="https://github.com/ninoseki/vscode-mogami/assets/291028/0cb02da2-2552-4f83-add9-f9dc91ecc141">

**Comment by moshfrid** [comment] 2024-05-26 17:27
thats weird. here i am on 0.0.20:
<img width="391" alt="image" src="https://github.com/ninoseki/vscode-mogami/assets/20837433/7f0d724b-099f-4ee7-980f-597efb2d4809">

and this is if I revert to 0.0.19:
<img width="246" alt="image" src="https://github.com/ninoseki/vscode-mogami/assets/20837433/fb4fc3c8-862e-4157-8cc3-e8f159acffaa">

same exact file.

**Comment by ninoseki** [comment] 2024-05-27 11:47
Hmm, just a confirmation, are you using Windows?

**Comment by moshfrid** [comment] 2024-05-27 15:40
yes

**Comment by ninoseki** [comment] 2024-05-28 00:05
I'm not sure but I guess Windows version has this issue (same as #37). A problem is that I don't have a Windows machine.

**Comment by ninoseki** [comment] 2024-05-28 11:24
I published v0.0.22 and it will be available in the marketplace soon.
It will have a basic logging feature. (Output > Mogami)
I will take a look If you could share the log from there and also `pyproject.toml` itself. Otherwise let me close this issue since it's not reproducible.

**Comment by ninoseki** [comment] 2024-06-05 12:44
Close this issue since there's no response

**Closed** 2024-06-05 12:44 UTC
